unbind r
bind r source-file ~/.tmux.conf

# Pane splits should open to the same path as the current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# vim mode
setw -g mode-keys vi

set -g mouse on

# start couting at 1
set -g base-index 1
setw -g pane-base-index 1

# select-pane via vim keybinds
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# reorder windows
set-option -g renumber-windows on
 
# TPM
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-plugins "time"
set -g @dracula-fixed-location "Berlin"
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-day-month true
set -g @dracula-show-timezone false
set -g @dracula-military-time true

set -g @dracula-refresh-rate 30

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
