# Pane splits should open to the same path as the current pane
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# vim mode
setw -g mode-keys vi

set -g mouse on

# start couting at 1
set -g base-index 1
setw -g pane-base-index 1

# select-pane via vim keybinds
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
 
